---
title: 'Linguistic Trivia '
author: Erwin Lares
date: '2018-07-17'
slug: linguistic-trivia
categories:
  - Linguistics
tags:
  - lexical items
subtitle: ''
summary: ''
authors: []
lastmod: '2021-05-27T00:26:03-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

# Linguistic trivia

I'm confused by the expression 'a piece of fruit.' Why not just a fruit? 

I used to think of fruit as a hypernym for all kinds of fruits. But it is behaves weirdly when compared to other hypernyms. When one has a lab and a chihuahua, for instance, one says 'two dogs'. The same is not true for one plum and one nectarine; it is not two fruits. 

Signs on school cafeterias read "one entree, one drink, one piece of fruit". The choices are oranges, apples, and bananas. The expectation is for people to grab a  whole apple, a whole banana or a whole orange. So 'fruit' is a mass noun and 'piece' is a measurement of fruit, right?

A mass noun is a homogeneous mass of something. Sand, water, milk, and mashed potatoes are all examples of mass nouns. To use them, we normally rely on coherent units of the mass nouns. Buckets of sand, gallons of water, glasses of milk, and mouthfuls of mashed potatoes are all good units. 

Pieces of fruit is then the way to use fruit. So speakers of English conceive fruit as a collective mass of all the different kinds of fruit mushed together? One is supposed to pick one out of this by using the unit "piece". I think 'fruit' in English is that concoction from which Fruit by the Foot™ is probably made: the mystery meat of fruits.
